[tool.flake8]
max-line-length = 120
exclude = [
    ".git",
    "__pycache__",
    "env",
    "venv",
    ".venv",
    "*.egg-info",
    ".tox",
    "dist",
    "build",
    ".vscode",
    ".pytest_cache",
    ".mypy_cache"
]
